title = "Configuración básica para detectar tokens, passwords y keys"

[allowlist]
description = "Permitir falsos positivos conocidos"
paths = []
commits = []
regexes = []

[[rules]]
id = "password-detect"
description = "Detecta posibles contraseñas"
regex = '''(?i)password\s*=\s*["']?[A-Za-z0-9!@#$%^&*()_+=-]{6,}["']?'''
tags = ["password"]

[[rules]]
id = "api-key-detect"
description = "Detecta claves API genéricas"
regex = '''(?i)api[_-]?key\s*=\s*["']?[A-Za-z0-9_\-]{16,}["']?'''
tags = ["apikey"]

[[rules]]
id = "token-detect"
description = "Detecta posibles tokens"
regex = '''(?i)token\s*=\s*["']?[A-Za-z0-9_\-]{8,}["']?'''
tags = ["token"]
